name: Docs workflow
on:
  workflow_dispatch:
  schedule:
    - cron: '0 15 * * 6'
permissions:
  contents: read

jobs:
  create:
    name: Create
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-20.04, ubuntu-18.04, windows-2019, macos-10.15]
        php-versions: ['5.3', '5.4', '5.5', '5.6', '7.0', '7.1', '7.2', '7.3', '7.4', '8.0', '8.1', '8.2']
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@cb605e52c26070c328afc4562f0b4ada7618a84e # v2.10.4
        with:
          egress-policy: audit

      - name: Setup PHP
        uses: shivammathur/setup-php@9e72090525849c5e82e596468b86eb55e9cc5401 # v2
        with:
          php-version: ${{ matrix.php-versions }}
      - name: Save unix
        env:
          file: php${{ matrix.php-versions }}-${{ matrix.operating-system }}.md
          version: ${{ matrix.php-versions }}
        if: matrix.operating-system != 'windows-2019'
        run: |
          echo "## PHP $version" >> "$file"
          printf "\n" >> "$file"
          echo "\`\`\`" >> "$file"
          php -m >> "$file"
          echo "\`\`\`" >> "$file"
          printf "\n" >> "$file"
      - name: Save Windows
        env:
          file: php${{ matrix.php-versions }}-${{ matrix.operating-system }}.md
          version: ${{ matrix.php-versions }}
        if: matrix.operating-system == 'windows-2019'
        run: |
          Write-Output "## PHP ${{ matrix.php-versions }}`n" | Out-File -FilePath "$env:file"
          Write-Output "``````" | Out-File -FilePath "$env:file" -Append
          php -m | Out-File -FilePath "$env:file" -Append
          Write-Output "```````n" | Out-File -FilePath "$env:file" -Append
      - uses: actions/upload-artifact@82c141cc518b40d92cc801eee768e7aafc9c2fa2 # v2.3.1
        with:
          name: lists
          path: php${{ matrix.php-versions }}-${{ matrix.operating-system }}.md
  update:
    permissions:
      contents: write  # for Git to git push
    name: Update
    needs: create
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@cb605e52c26070c328afc4562f0b4ada7618a84e # v2.10.4
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
        with:
          repository: ${{ github.repository }}.wiki
      - uses: actions/download-artifact@cbed621e49e4c01b044d60f6c80ea4ed6328b281 # v2.1.1
        with:
          path: ${{ github.workspace }}
      - name: Combine
        run: |
          git config --local user.email "${{ secrets.email }}"
          git config --local user.name "${{ github.repository_owner }}"
          for os in ubuntu-20.04 ubuntu-18.04 windows-2019 macos-10.15 macos-11; do
            echo "These are extensions which are loaded by default on the following PHP versions. More extensions which are available as packages and available on pecl are supported by setup-php. Refer to [php extension support](https://github.com/shivammathur/setup-php#heavy_plus_sign-php-extension-support) for more details." > Php-extensions-loaded-on-"$os".md
            for version in 5.3 5.4 5.5 5.6 7.0 7.1 7.2 7.3 7.4 8.0 8.1 8.2; do
              if [ "$os" = "macos-11" ]; then
                cat lists/php"$version"-macos-10.15.md >> Php-extensions-loaded-on-"$os".md
              else
                cat lists/php"$version"-"$os".md >> Php-extensions-loaded-on-"$os".md
              fi
            done
          done
          rm -rf ./lists
          if [ "$(git status --porcelain=v1 2>/dev/null | wc -l)" != "0" ]; then
            git add .
            git commit -m "Update PHP extensions on wiki - $(date +'%d-%m-%y')"
            git push -f https://${{ github.repository_owner }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.wiki.git master || true
          fi
